# In this notebook we are going to cover some of the most fundamental concept of tensors using TensorFlow 

More specifically, we are going to cover:
* Introduction to tensor
* Gentting information from tensor
* Manipulating tensor
* Tensor & numpy
* Using @tf.function (a way to speed up your regular Python function)
* Using GPUs with TensorFlow
* Exercise


## Introduction to Tensors

In [3]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.4.0


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the number of dimension of tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
#check dimension of our vector
vector.ndim

1

In [8]:
#create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
#check dimension of matrix
matrix.ndim

2

In [10]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,4.],
                             [8.,9.]], dtype=tf.float16) #specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 8.,  9.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
#check if gpu avaiable
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [13]:
#lets create tensor
tensor = tf.constant([[[1,2,3],
                     [4,5,6]],
                    [[7,8,9],
                    [10,11,12]],
                    [[13,14,15],
                    [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [14]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix: 2-dimentional array of number
* Tensor: an n-dimentional array of number 

### creating tensor with `tf.variable`

In [15]:
## create the same tensor but with tf.Vatiable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [16]:
# lets try change 1 of the element in changeable tensor
changeable_tensor[0] =7

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# lets try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
#lets try change unchangeable_tensor 
unchangeable_tensor[0].assign(7)

**Note:** Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensor, as tensor flow does this for you. However, if in doubt, use `tf.constant` and change it latef if needed.

### Creating random tensors
Random tensors are tensord of some abitrary size which contain random number

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2)) # create tensor from a normal distribution 
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))


# Are they equal?
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in tensor

In [ ]:
# Shuffle the tensor (valuable for when you want to shuffle your data so the inherit order doesnt effect learning)
not_shuffle = tf.constant([[10, 7],
                          [3, 4],
                          [2, 5]])
## shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffle)

In [ ]:
## shuffle our non-shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffle, seed=42)

**NOTE:** https://www.tensorflow.org/api_docs/python/tf/random/set_seed

## Other way to make tensor

In [ ]:
#create tensor all one
tf.ones([10,7])

In [ ]:
# create tensor all zero
tf.zeros(shape=(3,4))

### Turn numpy array to tensors

The main differen beetwen numpy array and tensorflow is that tensor can be run in a GPU (Much faster for numerical computing).

In [ ]:
# you can also turn numpy array into tensor
import numpy as np
numpy_A=np.arange(1,25,dtype=np.float16) #create numpy arange beetwen 1 to 25
numpy_A

# X = tf.constant(some_matrix) #capital for matrix
# y = tf,constant(vector) #non-capital for vector

In [ ]:
A= tf.constant(numpy_A, shape=(2,3,4))
B= tf.constant(numpy_A)
A,B 

### Getting Information from tensors

When dealing with tensors you probably want to be aware of the following attributes:

* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# create a rank 4 tensor (4 dimenstions)

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of out tensor
print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of Dimentions(Rank): ",rank_4_tensor.ndim)
print("Shape of our tensor:  ",rank_4_tensor.shape)
print("Element along the 0 axis: ",rank_4_tensor.shape[0])
print("Element along the last axis: ",rank_4_tensor.shape[-1])
print("Total mamber of elements in tensor: ",tf.size(rank_4_tensor).numpy())
print("Total mamber of elements in tensor: ",tf.size(rank_4_tensor))

### Indexing Tensors

Tensors can be indexed just like Python lists.

In [ ]:
some_list = [1,2,3,4]
some_list[:2]

In [ ]:
# Get the first 2 element of each dimension
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
#Get the first element from each dimension  except for the final one
rank_4_tensor[:1,:1,:1,:]

In [ ]:
# Create rank 2 tensor (2 dimentions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# get last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand tp final axis

In [ ]:
#expand the 0-axis 
tf.expand_dims(rank_2_tensor, axis=0)

### Manipulating tensor (tensor operations)

**Basic Operation**

`+`, `-`, `*`, `/`

In [ ]:
#  you can add values to a tensor using addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

In [ ]:
# Original tensor is unchanged
tensor

In [ ]:
#multiplication also worlk
tensor*10

In [ ]:
#subtraction 
tensor-10

In [ ]:
# we can use the tensor flow build in function too
tf.multiply(tensor,10)

**Matrix Multiplication**

In Machine Learning, matrix multiplication is one of the most common tensor operation

In [ ]:
#matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

In [ ]:
tensor_left = tf.constant([[1,2,5],
                          [7,2,1],
                          [3,3,3]])
tensor_right = tf.constant([[3,5],
                           [6,7],
                           [1,8]])

tf.matmul(tensor_left, tensor_right)

In [ ]:
#matrix multiplication with Python operator "@"
tensor @ tensor

In [ ]:
#create a (3,2) tensor
X = tf.constant([[1,2],
                [3,4],
                [5,6]])
#create another (3,2) tensor
Y =  tf.constant([[7,8],
                [9,10],
                [11,12]])

X,Y

In [ ]:
#try multiply X,Y
#tf.matmul(X,Y) error
#lets change the shape of y
tf.reshape(Y, shape=(2,3))

In [ ]:
#try matric multiply x by reshape y
tf.matmul(X,tf.reshape(Y, shape=(2,3)))

In [ ]:
X @ tf.reshape(Y, shape=(2,3))

In [ ]:
tf.matmul(tf.reshape(X, shape=(2,3)),Y)

In [ ]:
# WE can transpose the matrix
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

In [ ]:
#try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

**The dot product**

Matrix multiplication is also referred to the dot product

you can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
X,Y

In [ ]:
#perform the dot product on X and Y (required X or Y to be  transpose)
tf.tensordot(tf.transpose(X),Y, axes=1)


In [ ]:
# perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

In [ ]:
# perform matrix multiplication between X and Y (reshapo)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

In [ ]:
#check the value of Y. reshape Y, trasnpose Y
print("Normal: ")
print(Y,"\n")

print("Y reshape to (2,3): ")
print(tf.reshape(Y,shape=(2,3)),"\n")

print("Y transpose: ")
print(tf.transpose(Y),"\n")


Generally, when performing matrix multiplication on 2 tensor and one of the axes doesnt line up, you will transpose rather than reshape one of the tensor to satisfy the matrix multiplication rules.

### Changing the datatype of tensor

In [27]:
# create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [28]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [29]:
#change from float32 to float16 (reduce precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [30]:
# change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)